### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by HughxDev** [Wildhoney/DetectFont#1]
I am trying to use this in an Angular project, using Gulp to concat scripts together, etc. I include `node_modules/detect-font/dist/detect-font.js` along with all of my other dependencies and get this in the console:

> Uncaught ReferenceError: module is not defined

It points to a line in my compiled app.js that corresponds to the first line in detect-font.js: `module.exports =`.

I have tried including the package.json's stated dependency of is-element, but it didn't help. Are some of the devDependencies actually hard dependencies? Does this need Babel and React in order to run? I would suggest an elaboration in the README, so users know how to correctly install it.

**Comment by Wildhoney** [comment]
Sorry &mdash; once you've got it working, please update the README with a pull request for others who are having trouble.

It's essentially a ES6 module exported to CommonJS, so for the browser you will need to use something like [Webpack](https://webpack.github.io/) or [Rollup](https://github.com/rollup/rollup) to transpile your project &mdash; there is no global variable attached to `window` for example.
